export const GENERATION_CONFIG = {
  MAX_NEW_TOKENS: 128,
  NUM_BEAMS: 1,
  DO_SAMPLE: false,
  FP16_REPETITION_PENALTY: 1.25,

  // Sampling Defaults
  DEFAULT_TEMPERATURE: 1.0,
  DEFAULT_TOP_K: 40,
  DEFAULT_TOP_P: 0.9,
};
